### ISSUE TITLE
CloudFront 구성

### ISSUE THREAD

**Issue by ehtjsv2** [woowacourse-teams/2024-friendogly#151]
## 요구 사항
- 직접 S3 로 접근하기에는 보안에 취약점이 있기에 우테코에서 막아두었다.
- CloudFront를 통해서 S3에 접근하도록 구성하라.

**Comment by J-I-H-O** [comment]
> CloudFront를 통해서 S3에 접근하도록 구성하라.

비장하네요 ㅋㅋㅋㅋㅋ
