### ISSUE TITLE
모임 주소 정보 요청 및 저장 방식 변경

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse-teams/2024-friendogly#282]
## 요구 사항
- 주소 정보를 (도,광역시,특별시)/(시군구)/(읍면동) 으로 구분
- 참여 가능 모임 여부 로직의 논리적 오류 hotfix

**Comment by takoyakimchi** [comment]
`참여 가능 모임 여부 로직의 논리적 오류 hotfix`는 제가 반영하기는 했습니다!
