### ISSUE TITLE
사용하지 않는 파일 수정 및 삭제

### ISSUE THREAD

**Issue by takoyakimchi** [woowacourse-teams/2024-friendogly#288]
## 요구 사항
- `image/ImageController.java`는 업로드 테스트용 코드이므로, `dev`, `local` 환경에서만 작동하도록 한다.
- `test/TestController.java`는 사용하지 않는 코드이므로 삭제한다.

**Comment by ehtjsv2** [comment]
`image/ImageController.java`는 예제 코드가 아니라 이미지 put을 간편하게 하기 위한 코드입니다.

만약 저 컨트롤러가 없다면 image관련된 기능 관련된 테스트를 다른 도메인을 걸쳐서 해야해서 불편할 것 같습니다.

예를들어 삭제 했다면, jpeg도 들어가게 기능을 변경->(api테스트)->강아지등록api로 테스트->불편(붉은색)
삭제 안했다면 jpegd도 들어가게 기능 변경 -> image컨트롤러로 테스트-> 편안(파란색)

**Comment by takoyakimchi** [comment]
오 굿입니다 👍

**Comment by jimi567** [comment]
이 이슈에서 패키지도  수정하면 좋을 것 같아요
