### ISSUE TITLE
ALB 헬스체크 방향 수정

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse-teams/2024-friendogly#638]
## as-is
- 현재 로드밸런서는 존재하지 않는 api 경로로 요청을 보내 4xx번대 응답이 오는지 여부로 헬스체크를 수행하고 있음
- 존재하지 않는 경로로 요청을 보내는 경우는 WARN 레벨로 로깅하고 있음
- 헬스체크로 인한 WARN 로그가 너무 많아 다른 문제 상황이 가려지고 있음

![image](https://github.com/user-attachments/assets/69f71b2f-8642-479d-950f-22c9ea380f8a)

**Comment by ehtjsv2** [comment]
![image](https://github.com/user-attachments/assets/10bf0ea5-b522-4d5b-9371-e6419431d919)
