### ISSUE TITLE
공통 응답 포맷 만들기

### ISSUE THREAD

**Issue by takoyakimchi** [woowacourse-teams/2024-friendogly#94]
## 요구 사항
- status code, data 등을 포함한 공통 응답 포맷을 개발한다.

## 예시
**요청 성공 응답**
```json
{
  "isSuccess" : true,
  "data": {
    "email":"owner@naver.com",
    "name":"arin",
    "phone":"010-4321-4321",
    "role":"사장님"
  }
}
```

**요청 실패 응답** 
```json
{
  "isSuccess": false,
  "data": {
    "errorCode": "LOGIN_FAILED"
    "errorMessage": "sadfsdf"
    "detail": [
        "memberId는 필수 값입니다.",
        "name은 필수 값입니다."
    ]
  }
}
```

- `isSuccess` : 성공 여부 boolean 값
- `data` : 요청에 성공한 경우 실제 데이터, 실패한 경우 에러 객체
- `errorCode` : 안드로이드 측과 서로 합의한 우리만의 상태 코드
- `errorMessage` : 예외가 발생한 경우 예외 메시지
- `detail` : 에러 발생 원인 상세 정보

**Comment by J-I-H-O** [comment]
제가 해보겠습니당~
